version: "3.8"

services:
  mysql:
    image: 'mysql:8.2.0'
    environment:
      - 'MYSQL_DATABASE=books_management_api_db'
      - 'MYSQL_PASSWORD=P@ssw0rd'
      - 'MYSQL_ROOT_PASSWORD=P@ssw0rd'
      - 'MYSQL_USER=api_user'
    ports:
      - '3306:3306'
